### ISSUE TITLE
3.2.0 Eevee bug

### ISSUE THREAD

**Issue by FasterMars** [nalexandru/BlenderCompat#17]
Blender 3.2.0 crashes when switching to the Eevee renderer in the editor

**Comment by FasterMars** [comment]
[blender_debug_output.txt](https://github.com/nalexandru/BlenderCompat/files/8978539/blender_debug_output.txt)
[blender_system_info.txt](https://github.com/nalexandru/BlenderCompat/files/8978544/blender_system_info.txt)

These are the files, in the latest release, if I open Blender and switch to Eevee material preview mode, it blender freezes and never responds, the issue has slightly changed

**Comment by nalexandru** [comment]
I have looked at the logs and you are using an Intel HD Graphics 4000 GPU. This GPU is not supported by Blender and there are known issues with Eevee due to bugs in the driver:
https://code.blender.org/2019/04/supported-gpus-in-blender-2-80/#intel

I believe this is the cause of your issues (both crashing and freezing). Unfortunately, this is not something i can fix.

**Comment by FasterMars** [comment]
Thanks for the reply, I appreciate the effort!
