### ISSUE TITLE
Requests : Add another zip as debugging info and one without and compile with code optimization.

### ISSUE THREAD

**Issue by Illasera** [nalexandru/BlenderCompat#23]
The default version we are currently downloading from your github "Releases" comes with debugging files and make files.

Request 1 : Friend @nalexandru , most people don't need debugging information nor do they know what they are.
Which is why i suggest when uploading your releases to have the following files : 

Source code archives,
blender-x.x-windows-7.zip (For Release).
blender-x.x-debug-windows-7.zip 

Request 2 : Are you compiling with release config or debugging config?
I hope the code is compiled with maximum optimization flag on , If not; please compile with full optimization and strip binary data we don't need for release version.

**Comment by nalexandru** [comment]
1) You are correct, i assumed that what's in the output directory is clean of build artifacts. I will be removing them from future releases.

2) The binaries i upload are the result of running 'make release', so they should match the build flags of the official releases. (https://wiki.blender.org/wiki/Building_Blender/Options).

Regarding debugging information for Blender, the zip files from the build bot have blender.pdb in them and so does the installer:

![33msi](https://user-images.githubusercontent.com/9295849/190220637-ba6779d1-b728-4d82-b176-63ee92fcc656.PNG)

In order to match the official release as much as possible, i will be leaving that one in.

**Comment by Illasera** [comment]
Alright then its all good, Thank you.
