### ISSUE TITLE
Legacy GPU support

### ISSUE THREAD

**Issue by markkco** [nalexandru/BlenderCompat#25]
Any chance of legacy GPU support - ATI FirePro M7820? 
Blender 2.8 works ok, Blender 3.3.1 wont display grid and background, objects not displayed correctly.

![image](https://user-images.githubusercontent.com/29610318/200766415-bbab60cd-de07-4cbb-9ab7-d6eabd2dcc6d.png)

Debug files:
Note: when starting with blender_debug_gpu_glitchworkaround.cmd, grid, background and cube display correctly.
https://www.dropbox.com/sh/aj0xpbi7gd260s3/AABoLkCzMZIl8wfdsdxNeW14a?dl=0

**Comment by markkco** [comment]
After trying several blender versions (2.8.x - 2.9.x) from blender organisation, and versions 3.x.x from your github release page, blender has display problems or crashes on my system. Funny thing is that newer driver version has more problems than the older one. It's time for a hardware refresh...

Conclusion is that it's not worth anyone's time to bother with legacy hardware support, more so since Microsoft stopped windows 7 support.

I want to thank you for your time and work on blender support for windows 7.

**Comment by nalexandru** [comment]
I've checked the Blender system requirements (https://www.blender.org/download/requirements/). It says that Terrascale 2 GPUs have been deprecated since version 2.91, probably one of the reasons for this was the buggy driver situation that you encountered.

The idea behind this project is not to support older hardware, but to allow those that prefer Windows 7 to use Blender on supported hardware.

If a change in Blender breaks hardware on Windows 7 as was the case with issues #18 and #19 i will revert the change. For this issue this is not the case, fixing it would require workarounds for driver bugs, which as you said is not worth it.
