### ISSUE TITLE
Error when using CUDA in Cycles

### ISSUE THREAD

**Issue by Sergiarius** [nalexandru/BlenderCompat#3]
When I trying to use Cycles with CUDA (gpu+processor) active - it shows this error
![изображение_2021-11-29_173733](https://user-images.githubusercontent.com/95235815/143897303-b429486a-ae7b-4222-a75b-1fcabe03a18d.png)
and also don't render any lights(in any other versions of blender it works(on win 10-11, or those that earlier, that could work on win 7 too) (works only GPU compute without CUDA
When i tried to build it - error appears on trying to patch files apply bcompat7.patch 
![image](https://user-images.githubusercontent.com/95235815/143898063-67671203-b130-40a3-aa4c-8a054d300b0c.png)
also even if i will not try to patch it, but just update and use make/make.bat i'll have this error
![image](https://user-images.githubusercontent.com/95235815/143898431-8e700340-6086-4594-8d6c-d1fac0cd123c.png)
It could be great if any of those errors can be solved, because, with CUDA it really works faster(even if it with processor)

**Comment by nalexandru** [comment]
The CUDA error is because the binary i uploaded was compiled with CUDA 11.3 which doesn't have support for targetting cards with compute capability 3.0, so the kernel wasn't built. I will build it with CUDA 10 also.

I was unable to reproduce the patch error. Did you make any modifications to the files before applying the patch ?

**Comment by Sergiarius** [comment]
no, any

**Comment by nalexandru** [comment]
I wasn't able to make a full build with CUDA 10 because nvcc crashes with an internal error on the sm7.5 kernel, however i managed to build the kernel for GPUs with compute capability 3.0. I've uploaded the binaries here: [https://1drv.ms/u/s!AhpnXywMA4U1mTF-F-k19I17fE51](https://1drv.ms/u/s!AhpnXywMA4U1mTF-F-k19I17fE51).

**Comment by Sergiarius** [comment]
Thanks for fix and for this project at all. :)
