### ISSUE TITLE
cannot compile blender 3.4.1 in Ubuntu Linux 20.04

### ISSUE THREAD

**Issue by gfernval** [nalexandru/BlenderCompat#48]
After doing in Linux Ubuntu 20.04 "git clone https://projects.blender.org/blender/blender.git --branch v3.4.1" then do "cd blender" and "make update" (to get the prerequisites), Linux shows the error: "Blender git repository is in detached HEAD state, must be in a branch", what is the fault?

**Comment by nalexandru** [comment]
First, this project will not do anything for Linux systems. The changes are Windows specific.
If you want to cross-compile for Windows, i haven't tried it so i don't know if it will work. For 3.5 and up, you will have to build OpenEXR manually because the .cmd fill will not work on Linux.

The error you are getting is because you checked out a tag and `make update` will run `git pull` which fails with the error you are getting. I believe the solution is to download the dependencies manually, see "Download Libraries" from [https://wiki.blender.org/wiki/Building_Blender/Linux/Ubuntu](https://wiki.blender.org/wiki/Building_Blender/Linux/Ubuntu).

**Comment by gfernval** [comment]
Was successful in compiling Blender 3.3.7, not upper versions
