### ISSUE TITLE
Blender 4.0.2, Windows 7

### ISSUE THREAD

**Issue by Korchy** [nalexandru/BlenderCompat#82]
Downloaded from releases.

Blender starts, throws an error and closes.

ERROR (gpu.shader): overlay_motion_path_point VertShader: 
      | 
   15 | #define gpu_Array(_type) _type[]
      |                               ^
      | Error: '&' :  wrong operand types  no operation '&' exists that takes a left-hand operand of type 'attribute uint' and a right operand of type 'const bool' (or there is no acceptable conversion)
      | Error: '{' : syntax error syntax error

Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00000001439D2010
Module  : blender.exe
Thread  : 00001680
Writing: C:\Users\user\AppData\Local\Temp\blender.crash.txt

[blender_debug_output.txt](https://github.com/nalexandru/BlenderCompat/files/14523965/blender_debug_output.txt)
[blender_system_info.txt](https://github.com/nalexandru/BlenderCompat/files/14523966/blender_system_info.txt)

**Comment by nalexandru** [comment]
From the system info file, i see that you're running it on an Intel HD Graphics 4600 GPU. Unfortunately, support for the Intel HD4000 GPUs was dropped in 4.0 due to driver issues.
Version 3.6 LTS is the latest release (currently version [3.6.9](https://github.com/nalexandru/BlenderCompat/releases/tag/3.6.9)) that will run on your GPU.

**Comment by Korchy** [comment]
Thank you for the reply!
So the problem is on my side, I was inattentive to the list of graphic cards requirements (
